config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :reimbursements, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reimbursement.rb
class Reimbursement < ApplicationRecord
    def total
        ReimbursementCalculator.execute(self)
    end
end

app/models/reimbursement_calculator.rb
class ReimbursementCalculator
    def self.execute(reimbursement)
        reimbursement_hash = reimbursement.attributes
        cleaned_up_reimbursement = clean_up_reimbursement(reimbursement_hash)
        # OPTIMIZE This is where I should reach for other POROs instead of messing with an array of hashes.
        formatted_reimbursement = format_reimbursement(cleaned_up_reimbursement)
        non_duplicate_reimbursement = remove_reimbursement_duplicate_dates(formatted_reimbursement)
        sorted_reimbursement = non_duplicate_reimbursement.sort.to_h
       # TODO Figure out if there are gaps in the dates & then assign the dates as "full" or "travel" days.
       # TODO Assign the $ values for each day type & cost city type.
       # TODO Do the actual math that calculates the total.
    end

    private

    def self.clean_up_reimbursement(reimbursement_hash)
        # Remove the fields we do not care about
        reimbursement_hash.delete('id')
        reimbursement_hash.delete('created_at')
        reimbursement_hash.delete('updated_at')

        reimbursement_hash.map do |key, value|
            # make sure that every value is a string for the below logic 
            # since we deal with other data types.
            value = value.to_s

            if value.nil? || value.empty?
                reimbursement_hash.delete(key)
            end
        end

        return reimbursement_hash
    end

    def self.create_project_date_range(project_hash)
        cost_city = project_hash.values.first

        # We need to remove the cost_city hash becasue it is not needed.
        project_hash.delete(project_hash.keys.first)

        start_date = project_hash.values.first
        end_date = project_hash.values.last
        date_range = (start_date..end_date).to_a

        project_set_array = []

        date_range.each do |date|
            project_set_array << { date => cost_city }
        end

        return project_set_array
    end

    def self.format_reimbursement(cleaned_up_reimbursement)
        project_set_array = []
        i = 1
        # We divide by 3 here to calculate the "iteration_number" because that is 
        # how many key value pairs relate to each project.
        iteration_number = (cleaned_up_reimbursement.keys.count / 3) + 1
       
        while i < iteration_number  do
            project_hash = {}

            cleaned_up_reimbursement.each do |key, value|
                if key.include?(i.to_s)
                    project_hash[key] = value
                end
            end

            project_set_array << create_project_date_range(project_hash)

            i += 1
        end

        return project_set_array.flatten.uniq #calling .uniq here so we can preemptively remove the exact duplicates.
    end

    def self.remove_reimbursement_duplicate_dates(formatted_reimbursement)
        formatted_reimbursement.inject({}) do |new_hash, date_hash|
            key = date_hash.keys.first

            if !new_hash[key]
                new_hash[key] = date_hash[key]
            elsif new_hash[key] == 'low'
                new_hash[key] = date_hash[key]
            end
            
            new_hash
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reimbursements_controller.rb
class ReimbursementsController < ApplicationController
    def new
    end

    def create
        @reimbursement = Reimbursement.new(reimbursement_params)
        @reimbursement.save

        redirect_to @reimbursement
    end

    def show
        @reimbursement = Reimbursement.find_by_id(params[:id])
    end

    private

    def reimbursement_params
        params.permit(:cost_city_1, :start_date_1, :end_date_1, :cost_city_2, :start_date_2, :end_date_2, :cost_city_3, :start_date_3, :end_date_3, :cost_city_4, :start_date_4, :end_date_4)
    end
end

    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reimbursements_helper.rb
module ReimbursementsHelper
    def cost_cities
        %w(low high)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReimbursementCalculationSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reimbursements/new.html.erb
<h1> Welcome to the Reimbursement Calculation System! </h1>

<h4> Enter in the city cost type, start date, & end date for each of the projects in your set you want to calculate the reimbursement for. </h4>
<h4> Once you are finished entering in the details for all of your projects, click "Calcuate" and the system will calculate the correct reimbersement total for you. </h4>


<%= form_with model: @reimbursement, url: reimbursements_path(), method: :post do |form| %>
    <div class="project-container">
        <h2> Project 1 </h2>
        <%= form.label :cost_city_1, "City Cost Type:" %>
        <%= form.collection_select :cost_city_1, cost_cities(), :to_s, :to_s, :include_blank => true %>

        <%= form.label :start_date_1, "Project Start Date:" %>
        <%= form.date_select :start_date_1, :include_blank => true %>

        <%= form.label :end_date_1, "Project End Date:" %>
        <%= form.date_select :end_date_1, :include_blank => true %>
    </div>

    <div class="project-container">
        <h2> Project 2 </h2>
        <%= form.label :cost_city_2, "City Cost Type:" %>
        <%= form.collection_select :cost_city_2, cost_cities(), :to_s, :to_s, :include_blank => true %>

        <%= form.label :start_date_2, "Project Start Date:" %>
        <%= form.date_select :start_date_2, :include_blank => true %>

        <%= form.label :end_date_2, "Project End Date:" %>
        <%= form.date_select :end_date_2, :include_blank => true %>
    </div>

    <div class="project-container">
        <h2> Project 3 </h2>
        <%= form.label :cost_city_3, "City Cost Type:" %>
        <%= form.collection_select :cost_city_3, cost_cities(), :to_s, :to_s, :include_blank => true %>

        <%= form.label :start_date_3, "Project Start Date:" %>
        <%= form.date_select :start_date_3, :include_blank => true %>

        <%= form.label :end_date_3, "Project End Date:" %>
        <%= form.date_select :end_date_3, :include_blank => true %>
    </div>

    <div class="project-container">
        <h2> Project 4 </h2>
        <%= form.label :cost_city_4, "City Cost Type:" %>
        <%= form.collection_select :cost_city_4, cost_cities(), :to_s, :to_s, :include_blank => true %>

        <%= form.label :start_date_4, "Project Start Date:" %>
        <%= form.date_select :start_date_4, :include_blank => true %>

        <%= form.label :end_date_4, "Project End Date:" %>
        <%= form.date_select :end_date_4, :include_blank => true %>
    </div>

    <%= form.submit "Calculate" %> 
<% end %>

app/views/reimbursements/show.html.erb
<h1> Reimbursement Set Calculation </h1>

<h3> The total reimbersement for this set is:</h3>

<h2> $<%= @reimbursement.total %> </h2>